import { IconName } from "lucide-react/dynamic";
import { TTrackerColors } from "../_types/TTrackerColors";

const iconList: { name: IconName; category: string }[] = [
  { name: "piggy-bank", category: "finance" },
  { name: "hand-coins", category: "finance" },
  { name: "wallet", category: "finance" },
  { name: "wallet-minimal", category: "finance" },
  { name: "goal", category: "goal" },
  { name: "target", category: "goal" },
  { name: "circle-plus", category: "goal" },
  { name: "crosshair", category: "goal" },
  { name: "laptop", category: "electronics" },
  { name: "laptop-minimal", category: "electronics" },
  { name: "smartphone", category: "electronics" },
  { name: "headphones", category: "electronics" },
  { name: "headset", category: "electronics" },
  { name: "notebook", category: "stationery" },
  { name: "notebook-tabs", category: "stationery" },
  { name: "notebook-pen", category: "stationery" },
  { name: "party-popper", category: "celebration" },
  { name: "cake", category: "celebration" },
  { name: "cake-slice", category: "celebration" },
  { name: "sparkle", category: "celebration" },
  { name: "gift", category: "celebration" },
  { name: "flower", category: "nature" },
  { name: "flower-2", category: "nature" },
  { name: "leaf", category: "nature" },
  { name: "shirt", category: "clothing" },
  { name: "washing-machine", category: "appliance" },
  { name: "microwave", category: "appliance" },
  { name: "shopping-bag", category: "shopping" },
  { name: "shopping-cart", category: "shopping" },
  { name: "credit-card", category: "finance" },
  { name: "dollar-sign", category: "finance" },
  { name: "coins", category: "finance" },
  { name: "receipt", category: "finance" },
  { name: "chart-line", category: "finance" },
  { name: "chart-pie", category: "finance" },
  { name: "chart-bar", category: "finance" },
  { name: "calculator", category: "finance" },
  { name: "briefcase", category: "work" },
  { name: "home", category: "real-estate" },
  { name: "car", category: "transportation" },
  { name: "plane", category: "transportation" },
  { name: "train", category: "transportation" },
  { name: "bus", category: "transportation" },
  { name: "book", category: "education" },
  { name: "graduation-cap", category: "education" },
  { name: "medal", category: "achievement" },
  { name: "trophy", category: "achievement" },
  { name: "camera", category: "photography" },
  { name: "music", category: "entertainment" },
  { name: "film", category: "entertainment" },
  { name: "gamepad", category: "entertainment" },
  { name: "palette", category: "art" },
  { name: "brush", category: "art" },
  { name: "hammer", category: "tools" },
  { name: "wrench", category: "tools" },
  { name: "lightbulb", category: "ideas" },
  { name: "plug", category: "electronics" },
  { name: "battery", category: "electronics" },
  { name: "phone", category: "electronics" },
  { name: "tablet", category: "electronics" },
  { name: "printer", category: "electronics" },
  { name: "tv", category: "electronics" },
  { name: "watch", category: "accessories" },
  { name: "glasses", category: "accessories" },
  { name: "umbrella", category: "accessories" },
  { name: "key", category: "security" },
  { name: "lock", category: "security" },
  { name: "map", category: "navigation" },
  { name: "compass", category: "navigation" },
  { name: "globe", category: "navigation" },
  { name: "shopping-basket", category: "shopping" },
  { name: "box", category: "logistics" },
  { name: "package", category: "logistics" },
  { name: "truck", category: "logistics" },
  { name: "ship", category: "logistics" },
  { name: "rocket", category: "transportation" },
];

const iconCategories = Array.from(
  new Set(iconList.map((icon) => icon.category))
);

const colorList: TTrackerColors[] = [
  "green",
  "sky",
  "rose",
  "orange",
  "yellow",
  "violet",
  "slate",
];

export { iconList, iconCategories, colorList };
